---
all:
  children:
    rke2_servers:
      hosts:
        ok-infra:
          ansible_host: 192.168.100.2
          ansible_user: root
          rke2_type: server
          rke2_single_node: true
          hetzner_vswitch_interface: enp0s31f6  # verify with 'ip a' after delivery
          hetzner_vswitch_ip: 192.168.100.2

    rke2_agents:
      hosts:
        ok-gpu:
          ansible_host: 192.168.100.3
          ansible_user: root
          rke2_type: agent
          hetzner_vswitch_interface: enp4s0
          hetzner_vswitch_ip: 192.168.100.3
          rke2_gpu_node: true
