---
- name: Restart RKE2 server
  ansible.builtin.systemd:
    name: rke2-server
    state: restarted

- name: Restart RKE2 agent
  ansible.builtin.systemd:
    name: rke2-agent
    state: restarted

- name: Restart SSH
  ansible.builtin.systemd:
    name: ssh
    state: restarted

- name: Apply Netplan
  ansible.builtin.command:
    cmd: netplan apply
  changed_when: true
